run:
  skip-dirs:
    - ^internal/parser/test/tmptestdir.*

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2
  lll:
    line-length: 140

linters:
  enable-all: true
  disable:
    - scopelint
    - gochecknoglobals
    - gosec
    - testpackage
    - goerr113
    - wsl
    - whitespace
    - gofumpt
    - godox
    - godot
    - funlen
    - gofmt
    - goimports
    - misspell
issues:
  exclude-rules:
    - linters:
        - unparam
      text: always receives
    - linters:
        - staticcheck
      text: "SA9003:"
    - linters:
        - staticcheck
      text: "SA1019:"
    - linters:
        - stylecheck
      text: "ST1003:"
    - linters:
        - stylecheck
      text: "ST1019:"
    - linters:
        - gomnd
      text: "mnd:"

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
# service:
#   golangci-lint-version: 1.14.0 # use fixed version to not introduce new linters unexpectedly
