// Code generated by go-queryset. DO NOT EDIT.
package test

import (
	"errors"
	"fmt"
	"time"

	"github.com/zdevwu/go-queryset/internal/queryset/generator/tmp"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// ===== BEGIN of all query sets

// ===== BEGIN of query set BlogQuerySet

// BlogQuerySet is an queryset type for Blog
type BlogQuerySet struct {
	db *gorm.DB
}

// NewBlogQuerySet constructs new BlogQuerySet
func NewBlogQuerySet(db *gorm.DB) BlogQuerySet {
	return BlogQuerySet{
		db: db.Model(&Blog{}),
	}
}

func (qs BlogQuerySet) w(db *gorm.DB) BlogQuerySet {
	return NewBlogQuerySet(db)
}

func (qs BlogQuerySet) Select(fields ...BlogDBSchemaField) BlogQuerySet {
	names := []string{}
	for _, f := range fields {
		names = append(names, f.String())
	}

	return qs.w(qs.db.Select(names))
}

// Create is an autogenerated method
// nolint: dupl
func (o *Blog) Create(db *gorm.DB) error {
	return db.Create(o).Error
}

// Delete is an autogenerated method
// nolint: dupl
func (o *Blog) Delete(db *gorm.DB) error {
	return db.Delete(o).Error
}

// All is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) All(ret *[]Blog) error {
	return qs.db.Find(ret).Error
}

// Count is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) Count() (int64, error) {
	var count int64
	err := qs.db.Count(&count).Error
	return count, err
}

// CreatedAtEq is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) CreatedAtEq(createdAt time.Time) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Eq{Column: "created_at", Value: createdAt}))
}

// CreatedAtGt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) CreatedAtGt(createdAt time.Time) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Gt{Column: "created_at", Value: createdAt}))
}

// CreatedAtGte is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) CreatedAtGte(createdAt time.Time) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Gte{Column: "created_at", Value: createdAt}))
}

// CreatedAtLt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) CreatedAtLt(createdAt time.Time) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Lt{Column: "created_at", Value: createdAt}))
}

// CreatedAtLte is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) CreatedAtLte(createdAt time.Time) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Lte{Column: "created_at", Value: createdAt}))
}

// CreatedAtNe is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) CreatedAtNe(createdAt time.Time) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Neq{Column: "created_at", Value: createdAt}))
}

// Delete is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) Delete() error {
	return qs.db.Delete(&Blog{}).Error
}

// DeleteNum is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) DeleteNum() (int64, error) {
	db := qs.db.Delete(&Blog{})
	return db.RowsAffected, db.Error
}

// DeleteNumUnscoped is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) DeleteNumUnscoped() (int64, error) {
	db := qs.db.Unscoped().Delete(&Blog{})
	return db.RowsAffected, db.Error
}

// GetDB is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) GetDB() *gorm.DB {
	return qs.db
}

// GetUpdater is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) GetUpdater() BlogUpdater {
	return NewBlogUpdater(qs.db)
}

// IDEq is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) IDEq(ID uint) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Eq{Column: "id", Value: ID}))
}

// IDGt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) IDGt(ID uint) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Gt{Column: "id", Value: ID}))
}

// IDGte is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) IDGte(ID uint) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Gte{Column: "id", Value: ID}))
}

// IDIn is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) IDIn(ID ...uint) BlogQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in IDIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(ID))
	for i, s := range ID {
		values[i] = s
	}
	return qs.w(qs.db.Where(clause.IN{Column: "id", Values: values}))
}

// IDLt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) IDLt(ID uint) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Lt{Column: "id", Value: ID}))
}

// IDLte is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) IDLte(ID uint) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Lte{Column: "id", Value: ID}))
}

// IDNe is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) IDNe(ID uint) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Neq{Column: "id", Value: ID}))
}

// IDNotIn is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) IDNotIn(ID ...uint) BlogQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in IDNotIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(ID))
	for i, s := range ID {
		values[i] = s
	}
	return qs.w(qs.db.Where(clause.Not(clause.IN{Column: "id", Values: values})))
}

// Limit is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) Limit(limit int) BlogQuerySet {
	return qs.w(qs.db.Limit(limit))
}

// NameEq is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) NameEq(name string) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Eq{Column: "myname", Value: name}))
}

// NameGt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) NameGt(name string) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Gt{Column: "myname", Value: name}))
}

// NameGte is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) NameGte(name string) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Gte{Column: "myname", Value: name}))
}

// NameIn is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) NameIn(name ...string) BlogQuerySet {
	if len(name) == 0 {
		qs.db.AddError(errors.New("must at least pass one name in NameIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(name))
	for i, s := range name {
		values[i] = s
	}
	return qs.w(qs.db.Where(clause.IN{Column: "myname", Values: values}))
}

// NameLike is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) NameLike(name string) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Like{Column: "myname", Value: name}))
}

// NameLt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) NameLt(name string) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Lt{Column: "myname", Value: name}))
}

// NameLte is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) NameLte(name string) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Lte{Column: "myname", Value: name}))
}

// NameNe is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) NameNe(name string) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Neq{Column: "myname", Value: name}))
}

// NameNotIn is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) NameNotIn(name ...string) BlogQuerySet {
	if len(name) == 0 {
		qs.db.AddError(errors.New("must at least pass one name in NameNotIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(name))
	for i, s := range name {
		values[i] = s
	}
	return qs.w(qs.db.Where(clause.Not(clause.IN{Column: "myname", Values: values})))
}

// NameNotLike is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) NameNotLike(name string) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Not(clause.Like{Column: "myname", Value: name})))
}

// Offset is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) Offset(offset int) BlogQuerySet {
	return qs.w(qs.db.Offset(offset))
}

// One is used to retrieve one result. It returns gorm.ErrRecordNotFound
// if nothing was fetched
func (qs BlogQuerySet) One(ret *Blog) error {
	return qs.db.First(ret).Error
}

// OrCreatedAtEq is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrCreatedAtEq(createdAt time.Time) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Eq{Column: "created_at", Value: createdAt}))
}

// OrCreatedAtGt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrCreatedAtGt(createdAt time.Time) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Gt{Column: "created_at", Value: createdAt}))
}

// OrCreatedAtGte is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrCreatedAtGte(createdAt time.Time) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Gte{Column: "created_at", Value: createdAt}))
}

// OrCreatedAtLt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrCreatedAtLt(createdAt time.Time) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Lt{Column: "created_at", Value: createdAt}))
}

// OrCreatedAtLte is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrCreatedAtLte(createdAt time.Time) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Lte{Column: "created_at", Value: createdAt}))
}

// OrCreatedAtNe is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrCreatedAtNe(createdAt time.Time) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Neq{Column: "created_at", Value: createdAt}))
}

// OrIDEq is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrIDEq(ID uint) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Eq{Column: "id", Value: ID}))
}

// OrIDGt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrIDGt(ID uint) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Gt{Column: "id", Value: ID}))
}

// OrIDGte is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrIDGte(ID uint) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Gte{Column: "id", Value: ID}))
}

// OrIDIn is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrIDIn(ID ...uint) BlogQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in OrIDIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(ID))
	for i, s := range ID {
		values[i] = s
	}
	return qs.w(qs.db.Or(clause.IN{Column: "id", Values: values}))
}

// OrIDLt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrIDLt(ID uint) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Lt{Column: "id", Value: ID}))
}

// OrIDLte is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrIDLte(ID uint) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Lte{Column: "id", Value: ID}))
}

// OrIDNe is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrIDNe(ID uint) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Neq{Column: "id", Value: ID}))
}

// OrIDNotIn is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrIDNotIn(ID ...uint) BlogQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in OrIDNotIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(ID))
	for i, s := range ID {
		values[i] = s
	}
	return qs.w(qs.db.Or(clause.Not(clause.IN{Column: "id", Values: values})))
}

// OrNameEq is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrNameEq(name string) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Eq{Column: "myname", Value: name}))
}

// OrNameGt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrNameGt(name string) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Gt{Column: "myname", Value: name}))
}

// OrNameGte is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrNameGte(name string) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Gte{Column: "myname", Value: name}))
}

// OrNameIn is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrNameIn(name ...string) BlogQuerySet {
	if len(name) == 0 {
		qs.db.AddError(errors.New("must at least pass one name in OrNameIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(name))
	for i, s := range name {
		values[i] = s
	}
	return qs.w(qs.db.Or(clause.IN{Column: "myname", Values: values}))
}

// OrNameLike is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrNameLike(name string) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Like{Column: "myname", Value: name}))
}

// OrNameLt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrNameLt(name string) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Lt{Column: "myname", Value: name}))
}

// OrNameLte is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrNameLte(name string) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Lte{Column: "myname", Value: name}))
}

// OrNameNe is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrNameNe(name string) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Neq{Column: "myname", Value: name}))
}

// OrNameNotIn is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrNameNotIn(name ...string) BlogQuerySet {
	if len(name) == 0 {
		qs.db.AddError(errors.New("must at least pass one name in OrNameNotIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(name))
	for i, s := range name {
		values[i] = s
	}
	return qs.w(qs.db.Or(clause.Not(clause.IN{Column: "myname", Values: values})))
}

// OrNameNotLike is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrNameNotLike(name string) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Not(clause.Like{Column: "myname", Value: name})))
}

// OrUpdatedAtEq is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrUpdatedAtEq(updatedAt time.Time) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Eq{Column: "updated_at", Value: updatedAt}))
}

// OrUpdatedAtGt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrUpdatedAtGt(updatedAt time.Time) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Gt{Column: "updated_at", Value: updatedAt}))
}

// OrUpdatedAtGte is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrUpdatedAtGte(updatedAt time.Time) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Gte{Column: "updated_at", Value: updatedAt}))
}

// OrUpdatedAtLt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrUpdatedAtLt(updatedAt time.Time) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Lt{Column: "updated_at", Value: updatedAt}))
}

// OrUpdatedAtLte is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrUpdatedAtLte(updatedAt time.Time) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Lte{Column: "updated_at", Value: updatedAt}))
}

// OrUpdatedAtNe is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrUpdatedAtNe(updatedAt time.Time) BlogQuerySet {
	return qs.w(qs.db.Or(clause.Neq{Column: "updated_at", Value: updatedAt}))
}

// OrderAscByCreatedAt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrderAscByCreatedAt() BlogQuerySet {
	return qs.w(qs.db.Order("created_at ASC"))
}

// OrderAscByID is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrderAscByID() BlogQuerySet {
	return qs.w(qs.db.Order("id ASC"))
}

// OrderAscByName is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrderAscByName() BlogQuerySet {
	return qs.w(qs.db.Order("myname ASC"))
}

// OrderAscByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrderAscByUpdatedAt() BlogQuerySet {
	return qs.w(qs.db.Order("updated_at ASC"))
}

// OrderDescByCreatedAt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrderDescByCreatedAt() BlogQuerySet {
	return qs.w(qs.db.Order("created_at DESC"))
}

// OrderDescByID is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrderDescByID() BlogQuerySet {
	return qs.w(qs.db.Order("id DESC"))
}

// OrderDescByName is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrderDescByName() BlogQuerySet {
	return qs.w(qs.db.Order("myname DESC"))
}

// OrderDescByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) OrderDescByUpdatedAt() BlogQuerySet {
	return qs.w(qs.db.Order("updated_at DESC"))
}

// PreloadDeletedAt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) PreloadDeletedAt() BlogQuerySet {
	return qs.w(qs.db.Preload("DeletedAt"))
}

// UpdatedAtEq is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) UpdatedAtEq(updatedAt time.Time) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Eq{Column: "updated_at", Value: updatedAt}))
}

// UpdatedAtGt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) UpdatedAtGt(updatedAt time.Time) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Gt{Column: "updated_at", Value: updatedAt}))
}

// UpdatedAtGte is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) UpdatedAtGte(updatedAt time.Time) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Gte{Column: "updated_at", Value: updatedAt}))
}

// UpdatedAtLt is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) UpdatedAtLt(updatedAt time.Time) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Lt{Column: "updated_at", Value: updatedAt}))
}

// UpdatedAtLte is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) UpdatedAtLte(updatedAt time.Time) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Lte{Column: "updated_at", Value: updatedAt}))
}

// UpdatedAtNe is an autogenerated method
// nolint: dupl
func (qs BlogQuerySet) UpdatedAtNe(updatedAt time.Time) BlogQuerySet {
	return qs.w(qs.db.Where(clause.Neq{Column: "updated_at", Value: updatedAt}))
}

// SetCreatedAt is an autogenerated method
// nolint: dupl
func (u BlogUpdater) SetCreatedAt(createdAt time.Time) BlogUpdater {
	u.fields[string(BlogDBSchema.CreatedAt)] = createdAt
	return u
}

// SetDeletedAt is an autogenerated method
// nolint: dupl
func (u BlogUpdater) SetDeletedAt(deletedAt gorm.DeletedAt) BlogUpdater {
	u.fields[string(BlogDBSchema.DeletedAt)] = deletedAt
	return u
}

// SetID is an autogenerated method
// nolint: dupl
func (u BlogUpdater) SetID(ID uint) BlogUpdater {
	u.fields[string(BlogDBSchema.ID)] = ID
	return u
}

// SetName is an autogenerated method
// nolint: dupl
func (u BlogUpdater) SetName(name string) BlogUpdater {
	u.fields[string(BlogDBSchema.Name)] = name
	return u
}

// SetUpdatedAt is an autogenerated method
// nolint: dupl
func (u BlogUpdater) SetUpdatedAt(updatedAt time.Time) BlogUpdater {
	u.fields[string(BlogDBSchema.UpdatedAt)] = updatedAt
	return u
}

// Update is an autogenerated method
// nolint: dupl
func (u BlogUpdater) Update() error {
	return u.db.Updates(u.fields).Error
}

// UpdateNum is an autogenerated method
// nolint: dupl
func (u BlogUpdater) UpdateNum() (int64, error) {
	db := u.db.Updates(u.fields)
	return db.RowsAffected, db.Error
}

// ===== END of query set BlogQuerySet

// ===== BEGIN of Blog modifiers

// BlogDBSchemaField describes database schema field. It requires for method 'Update'
type BlogDBSchemaField string

// String method returns string representation of field.
// nolint: dupl
func (f BlogDBSchemaField) String() string {
	return string(f)
}

// BlogDBSchema stores db field names of Blog
var BlogDBSchema = struct {
	ID        BlogDBSchemaField
	CreatedAt BlogDBSchemaField
	UpdatedAt BlogDBSchemaField
	DeletedAt BlogDBSchemaField
	Name      BlogDBSchemaField
}{

	ID:        BlogDBSchemaField("id"),
	CreatedAt: BlogDBSchemaField("created_at"),
	UpdatedAt: BlogDBSchemaField("updated_at"),
	DeletedAt: BlogDBSchemaField("deleted_at"),
	Name:      BlogDBSchemaField("myname"),
}

var BlogDBSchemaAllFields = []BlogDBSchemaField{

	BlogDBSchema.ID,
	BlogDBSchema.CreatedAt,
	BlogDBSchema.UpdatedAt,
	BlogDBSchema.DeletedAt,
	BlogDBSchema.Name,
}

// Update updates Blog fields by primary key
// nolint: dupl
func (o *Blog) Update(db *gorm.DB, fields ...BlogDBSchemaField) error {
	dbNameToFieldName := map[string]interface{}{
		"id":         o.ID,
		"created_at": o.CreatedAt,
		"updated_at": o.UpdatedAt,
		"deleted_at": o.DeletedAt,
		"myname":     o.Name,
	}
	u := map[string]interface{}{}
	for _, f := range fields {
		fs := f.String()
		u[fs] = dbNameToFieldName[fs]
	}
	if err := db.Model(o).Updates(u).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return err
		}

		return fmt.Errorf("can't update Blog %v fields %v: %s",
			o, fields, err)
	}

	return nil
}

// BlogUpdater is an Blog updates manager
type BlogUpdater struct {
	fields map[string]interface{}
	db     *gorm.DB
}

// NewBlogUpdater creates new Blog updater
// nolint: dupl
func NewBlogUpdater(db *gorm.DB) BlogUpdater {
	return BlogUpdater{
		fields: map[string]interface{}{},
		db:     db.Model(&Blog{}),
	}
}

// ===== END of Blog modifiers

// ===== BEGIN of query set CheckReservedKeywordsQuerySet

// CheckReservedKeywordsQuerySet is an queryset type for CheckReservedKeywords
type CheckReservedKeywordsQuerySet struct {
	db *gorm.DB
}

// NewCheckReservedKeywordsQuerySet constructs new CheckReservedKeywordsQuerySet
func NewCheckReservedKeywordsQuerySet(db *gorm.DB) CheckReservedKeywordsQuerySet {
	return CheckReservedKeywordsQuerySet{
		db: db.Model(&CheckReservedKeywords{}),
	}
}

func (qs CheckReservedKeywordsQuerySet) w(db *gorm.DB) CheckReservedKeywordsQuerySet {
	return NewCheckReservedKeywordsQuerySet(db)
}

func (qs CheckReservedKeywordsQuerySet) Select(fields ...CheckReservedKeywordsDBSchemaField) CheckReservedKeywordsQuerySet {
	names := []string{}
	for _, f := range fields {
		names = append(names, f.String())
	}

	return qs.w(qs.db.Select(names))
}

// Create is an autogenerated method
// nolint: dupl
func (o *CheckReservedKeywords) Create(db *gorm.DB) error {
	return db.Create(o).Error
}

// Delete is an autogenerated method
// nolint: dupl
func (o *CheckReservedKeywords) Delete(db *gorm.DB) error {
	return db.Delete(o).Error
}

// All is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) All(ret *[]CheckReservedKeywords) error {
	return qs.db.Find(ret).Error
}

// Count is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) Count() (int64, error) {
	var count int64
	err := qs.db.Count(&count).Error
	return count, err
}

// Delete is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) Delete() error {
	return qs.db.Delete(&CheckReservedKeywords{}).Error
}

// DeleteNum is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) DeleteNum() (int64, error) {
	db := qs.db.Delete(&CheckReservedKeywords{})
	return db.RowsAffected, db.Error
}

// DeleteNumUnscoped is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) DeleteNumUnscoped() (int64, error) {
	db := qs.db.Unscoped().Delete(&CheckReservedKeywords{})
	return db.RowsAffected, db.Error
}

// GetDB is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) GetDB() *gorm.DB {
	return qs.db
}

// GetUpdater is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) GetUpdater() CheckReservedKeywordsUpdater {
	return NewCheckReservedKeywordsUpdater(qs.db)
}

// Limit is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) Limit(limit int) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Limit(limit))
}

// Offset is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) Offset(offset int) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Offset(offset))
}

// One is used to retrieve one result. It returns gorm.ErrRecordNotFound
// if nothing was fetched
func (qs CheckReservedKeywordsQuerySet) One(ret *CheckReservedKeywords) error {
	return qs.db.First(ret).Error
}

// OrStructEq is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) OrStructEq(structValue int) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Or(clause.Eq{Column: "struct", Value: structValue}))
}

// OrStructGt is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) OrStructGt(structValue int) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Or(clause.Gt{Column: "struct", Value: structValue}))
}

// OrStructGte is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) OrStructGte(structValue int) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Or(clause.Gte{Column: "struct", Value: structValue}))
}

// OrStructIn is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) OrStructIn(structValue ...int) CheckReservedKeywordsQuerySet {
	if len(structValue) == 0 {
		qs.db.AddError(errors.New("must at least pass one structValue in OrStructIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(structValue))
	for i, s := range structValue {
		values[i] = s
	}
	return qs.w(qs.db.Or(clause.IN{Column: "struct", Values: values}))
}

// OrStructLt is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) OrStructLt(structValue int) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Or(clause.Lt{Column: "struct", Value: structValue}))
}

// OrStructLte is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) OrStructLte(structValue int) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Or(clause.Lte{Column: "struct", Value: structValue}))
}

// OrStructNe is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) OrStructNe(structValue int) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Or(clause.Neq{Column: "struct", Value: structValue}))
}

// OrStructNotIn is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) OrStructNotIn(structValue ...int) CheckReservedKeywordsQuerySet {
	if len(structValue) == 0 {
		qs.db.AddError(errors.New("must at least pass one structValue in OrStructNotIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(structValue))
	for i, s := range structValue {
		values[i] = s
	}
	return qs.w(qs.db.Or(clause.Not(clause.IN{Column: "struct", Values: values})))
}

// OrTypeEq is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) OrTypeEq(typeValue string) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Or(clause.Eq{Column: "type", Value: typeValue}))
}

// OrTypeGt is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) OrTypeGt(typeValue string) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Or(clause.Gt{Column: "type", Value: typeValue}))
}

// OrTypeGte is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) OrTypeGte(typeValue string) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Or(clause.Gte{Column: "type", Value: typeValue}))
}

// OrTypeIn is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) OrTypeIn(typeValue ...string) CheckReservedKeywordsQuerySet {
	if len(typeValue) == 0 {
		qs.db.AddError(errors.New("must at least pass one typeValue in OrTypeIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(typeValue))
	for i, s := range typeValue {
		values[i] = s
	}
	return qs.w(qs.db.Or(clause.IN{Column: "type", Values: values}))
}

// OrTypeLike is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) OrTypeLike(typeValue string) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Or(clause.Like{Column: "type", Value: typeValue}))
}

// OrTypeLt is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) OrTypeLt(typeValue string) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Or(clause.Lt{Column: "type", Value: typeValue}))
}

// OrTypeLte is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) OrTypeLte(typeValue string) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Or(clause.Lte{Column: "type", Value: typeValue}))
}

// OrTypeNe is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) OrTypeNe(typeValue string) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Or(clause.Neq{Column: "type", Value: typeValue}))
}

// OrTypeNotIn is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) OrTypeNotIn(typeValue ...string) CheckReservedKeywordsQuerySet {
	if len(typeValue) == 0 {
		qs.db.AddError(errors.New("must at least pass one typeValue in OrTypeNotIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(typeValue))
	for i, s := range typeValue {
		values[i] = s
	}
	return qs.w(qs.db.Or(clause.Not(clause.IN{Column: "type", Values: values})))
}

// OrTypeNotLike is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) OrTypeNotLike(typeValue string) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Or(clause.Not(clause.Like{Column: "type", Value: typeValue})))
}

// OrderAscByStruct is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) OrderAscByStruct() CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Order("struct ASC"))
}

// OrderAscByType is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) OrderAscByType() CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Order("type ASC"))
}

// OrderDescByStruct is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) OrderDescByStruct() CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Order("struct DESC"))
}

// OrderDescByType is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) OrderDescByType() CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Order("type DESC"))
}

// StructEq is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) StructEq(structValue int) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Where(clause.Eq{Column: "struct", Value: structValue}))
}

// StructGt is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) StructGt(structValue int) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Where(clause.Gt{Column: "struct", Value: structValue}))
}

// StructGte is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) StructGte(structValue int) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Where(clause.Gte{Column: "struct", Value: structValue}))
}

// StructIn is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) StructIn(structValue ...int) CheckReservedKeywordsQuerySet {
	if len(structValue) == 0 {
		qs.db.AddError(errors.New("must at least pass one structValue in StructIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(structValue))
	for i, s := range structValue {
		values[i] = s
	}
	return qs.w(qs.db.Where(clause.IN{Column: "struct", Values: values}))
}

// StructLt is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) StructLt(structValue int) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Where(clause.Lt{Column: "struct", Value: structValue}))
}

// StructLte is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) StructLte(structValue int) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Where(clause.Lte{Column: "struct", Value: structValue}))
}

// StructNe is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) StructNe(structValue int) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Where(clause.Neq{Column: "struct", Value: structValue}))
}

// StructNotIn is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) StructNotIn(structValue ...int) CheckReservedKeywordsQuerySet {
	if len(structValue) == 0 {
		qs.db.AddError(errors.New("must at least pass one structValue in StructNotIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(structValue))
	for i, s := range structValue {
		values[i] = s
	}
	return qs.w(qs.db.Where(clause.Not(clause.IN{Column: "struct", Values: values})))
}

// TypeEq is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) TypeEq(typeValue string) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Where(clause.Eq{Column: "type", Value: typeValue}))
}

// TypeGt is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) TypeGt(typeValue string) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Where(clause.Gt{Column: "type", Value: typeValue}))
}

// TypeGte is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) TypeGte(typeValue string) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Where(clause.Gte{Column: "type", Value: typeValue}))
}

// TypeIn is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) TypeIn(typeValue ...string) CheckReservedKeywordsQuerySet {
	if len(typeValue) == 0 {
		qs.db.AddError(errors.New("must at least pass one typeValue in TypeIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(typeValue))
	for i, s := range typeValue {
		values[i] = s
	}
	return qs.w(qs.db.Where(clause.IN{Column: "type", Values: values}))
}

// TypeLike is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) TypeLike(typeValue string) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Where(clause.Like{Column: "type", Value: typeValue}))
}

// TypeLt is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) TypeLt(typeValue string) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Where(clause.Lt{Column: "type", Value: typeValue}))
}

// TypeLte is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) TypeLte(typeValue string) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Where(clause.Lte{Column: "type", Value: typeValue}))
}

// TypeNe is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) TypeNe(typeValue string) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Where(clause.Neq{Column: "type", Value: typeValue}))
}

// TypeNotIn is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) TypeNotIn(typeValue ...string) CheckReservedKeywordsQuerySet {
	if len(typeValue) == 0 {
		qs.db.AddError(errors.New("must at least pass one typeValue in TypeNotIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(typeValue))
	for i, s := range typeValue {
		values[i] = s
	}
	return qs.w(qs.db.Where(clause.Not(clause.IN{Column: "type", Values: values})))
}

// TypeNotLike is an autogenerated method
// nolint: dupl
func (qs CheckReservedKeywordsQuerySet) TypeNotLike(typeValue string) CheckReservedKeywordsQuerySet {
	return qs.w(qs.db.Where(clause.Not(clause.Like{Column: "type", Value: typeValue})))
}

// SetStruct is an autogenerated method
// nolint: dupl
func (u CheckReservedKeywordsUpdater) SetStruct(structValue int) CheckReservedKeywordsUpdater {
	u.fields[string(CheckReservedKeywordsDBSchema.Struct)] = structValue
	return u
}

// SetType is an autogenerated method
// nolint: dupl
func (u CheckReservedKeywordsUpdater) SetType(typeValue string) CheckReservedKeywordsUpdater {
	u.fields[string(CheckReservedKeywordsDBSchema.Type)] = typeValue
	return u
}

// Update is an autogenerated method
// nolint: dupl
func (u CheckReservedKeywordsUpdater) Update() error {
	return u.db.Updates(u.fields).Error
}

// UpdateNum is an autogenerated method
// nolint: dupl
func (u CheckReservedKeywordsUpdater) UpdateNum() (int64, error) {
	db := u.db.Updates(u.fields)
	return db.RowsAffected, db.Error
}

// ===== END of query set CheckReservedKeywordsQuerySet

// ===== BEGIN of CheckReservedKeywords modifiers

// CheckReservedKeywordsDBSchemaField describes database schema field. It requires for method 'Update'
type CheckReservedKeywordsDBSchemaField string

// String method returns string representation of field.
// nolint: dupl
func (f CheckReservedKeywordsDBSchemaField) String() string {
	return string(f)
}

// CheckReservedKeywordsDBSchema stores db field names of CheckReservedKeywords
var CheckReservedKeywordsDBSchema = struct {
	Type   CheckReservedKeywordsDBSchemaField
	Struct CheckReservedKeywordsDBSchemaField
}{

	Type:   CheckReservedKeywordsDBSchemaField("type"),
	Struct: CheckReservedKeywordsDBSchemaField("struct"),
}

var CheckReservedKeywordsDBSchemaAllFields = []CheckReservedKeywordsDBSchemaField{

	CheckReservedKeywordsDBSchema.Type,
	CheckReservedKeywordsDBSchema.Struct,
}

// Update updates CheckReservedKeywords fields by primary key
// nolint: dupl
func (o *CheckReservedKeywords) Update(db *gorm.DB, fields ...CheckReservedKeywordsDBSchemaField) error {
	dbNameToFieldName := map[string]interface{}{
		"type":   o.Type,
		"struct": o.Struct,
	}
	u := map[string]interface{}{}
	for _, f := range fields {
		fs := f.String()
		u[fs] = dbNameToFieldName[fs]
	}
	if err := db.Model(o).Updates(u).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return err
		}

		return fmt.Errorf("can't update CheckReservedKeywords %v fields %v: %s",
			o, fields, err)
	}

	return nil
}

// CheckReservedKeywordsUpdater is an CheckReservedKeywords updates manager
type CheckReservedKeywordsUpdater struct {
	fields map[string]interface{}
	db     *gorm.DB
}

// NewCheckReservedKeywordsUpdater creates new CheckReservedKeywords updater
// nolint: dupl
func NewCheckReservedKeywordsUpdater(db *gorm.DB) CheckReservedKeywordsUpdater {
	return CheckReservedKeywordsUpdater{
		fields: map[string]interface{}{},
		db:     db.Model(&CheckReservedKeywords{}),
	}
}

// ===== END of CheckReservedKeywords modifiers

// ===== BEGIN of query set PostQuerySet

// PostQuerySet is an queryset type for Post
type PostQuerySet struct {
	db *gorm.DB
}

// NewPostQuerySet constructs new PostQuerySet
func NewPostQuerySet(db *gorm.DB) PostQuerySet {
	return PostQuerySet{
		db: db.Model(&Post{}),
	}
}

func (qs PostQuerySet) w(db *gorm.DB) PostQuerySet {
	return NewPostQuerySet(db)
}

func (qs PostQuerySet) Select(fields ...PostDBSchemaField) PostQuerySet {
	names := []string{}
	for _, f := range fields {
		names = append(names, f.String())
	}

	return qs.w(qs.db.Select(names))
}

// Create is an autogenerated method
// nolint: dupl
func (o *Post) Create(db *gorm.DB) error {
	return db.Create(o).Error
}

// Delete is an autogenerated method
// nolint: dupl
func (o *Post) Delete(db *gorm.DB) error {
	return db.Delete(o).Error
}

// All is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) All(ret *[]Post) error {
	return qs.db.Find(ret).Error
}

// BlogIsNotNull is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) BlogIsNotNull() PostQuerySet {
	return qs.w(qs.db.Where("blog IS NOT NULL"))
}

// BlogIsNull is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) BlogIsNull() PostQuerySet {
	return qs.w(qs.db.Where("blog IS NULL"))
}

// Count is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) Count() (int64, error) {
	var count int64
	err := qs.db.Count(&count).Error
	return count, err
}

// CreatedAtEq is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) CreatedAtEq(createdAt time.Time) PostQuerySet {
	return qs.w(qs.db.Where(clause.Eq{Column: "created_at", Value: createdAt}))
}

// CreatedAtGt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) CreatedAtGt(createdAt time.Time) PostQuerySet {
	return qs.w(qs.db.Where(clause.Gt{Column: "created_at", Value: createdAt}))
}

// CreatedAtGte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) CreatedAtGte(createdAt time.Time) PostQuerySet {
	return qs.w(qs.db.Where(clause.Gte{Column: "created_at", Value: createdAt}))
}

// CreatedAtLt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) CreatedAtLt(createdAt time.Time) PostQuerySet {
	return qs.w(qs.db.Where(clause.Lt{Column: "created_at", Value: createdAt}))
}

// CreatedAtLte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) CreatedAtLte(createdAt time.Time) PostQuerySet {
	return qs.w(qs.db.Where(clause.Lte{Column: "created_at", Value: createdAt}))
}

// CreatedAtNe is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) CreatedAtNe(createdAt time.Time) PostQuerySet {
	return qs.w(qs.db.Where(clause.Neq{Column: "created_at", Value: createdAt}))
}

// Delete is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) Delete() error {
	return qs.db.Delete(&Post{}).Error
}

// DeleteNum is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) DeleteNum() (int64, error) {
	db := qs.db.Delete(&Post{})
	return db.RowsAffected, db.Error
}

// DeleteNumUnscoped is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) DeleteNumUnscoped() (int64, error) {
	db := qs.db.Unscoped().Delete(&Post{})
	return db.RowsAffected, db.Error
}

// GetDB is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) GetDB() *gorm.DB {
	return qs.db
}

// GetUpdater is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) GetUpdater() PostUpdater {
	return NewPostUpdater(qs.db)
}

// IDEq is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) IDEq(ID uint) PostQuerySet {
	return qs.w(qs.db.Where(clause.Eq{Column: "id", Value: ID}))
}

// IDGt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) IDGt(ID uint) PostQuerySet {
	return qs.w(qs.db.Where(clause.Gt{Column: "id", Value: ID}))
}

// IDGte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) IDGte(ID uint) PostQuerySet {
	return qs.w(qs.db.Where(clause.Gte{Column: "id", Value: ID}))
}

// IDIn is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) IDIn(ID ...uint) PostQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in IDIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(ID))
	for i, s := range ID {
		values[i] = s
	}
	return qs.w(qs.db.Where(clause.IN{Column: "id", Values: values}))
}

// IDLt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) IDLt(ID uint) PostQuerySet {
	return qs.w(qs.db.Where(clause.Lt{Column: "id", Value: ID}))
}

// IDLte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) IDLte(ID uint) PostQuerySet {
	return qs.w(qs.db.Where(clause.Lte{Column: "id", Value: ID}))
}

// IDNe is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) IDNe(ID uint) PostQuerySet {
	return qs.w(qs.db.Where(clause.Neq{Column: "id", Value: ID}))
}

// IDNotIn is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) IDNotIn(ID ...uint) PostQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in IDNotIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(ID))
	for i, s := range ID {
		values[i] = s
	}
	return qs.w(qs.db.Where(clause.Not(clause.IN{Column: "id", Values: values})))
}

// Limit is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) Limit(limit int) PostQuerySet {
	return qs.w(qs.db.Limit(limit))
}

// Offset is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) Offset(offset int) PostQuerySet {
	return qs.w(qs.db.Offset(offset))
}

// One is used to retrieve one result. It returns gorm.ErrRecordNotFound
// if nothing was fetched
func (qs PostQuerySet) One(ret *Post) error {
	return qs.db.First(ret).Error
}

// OrBlogIsNotNull is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrBlogIsNotNull() PostQuerySet {
	return qs.w(qs.db.Or("blog IS NOT NULL"))
}

// OrBlogIsNull is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrBlogIsNull() PostQuerySet {
	return qs.w(qs.db.Or("blog IS NULL"))
}

// OrCreatedAtEq is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrCreatedAtEq(createdAt time.Time) PostQuerySet {
	return qs.w(qs.db.Or(clause.Eq{Column: "created_at", Value: createdAt}))
}

// OrCreatedAtGt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrCreatedAtGt(createdAt time.Time) PostQuerySet {
	return qs.w(qs.db.Or(clause.Gt{Column: "created_at", Value: createdAt}))
}

// OrCreatedAtGte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrCreatedAtGte(createdAt time.Time) PostQuerySet {
	return qs.w(qs.db.Or(clause.Gte{Column: "created_at", Value: createdAt}))
}

// OrCreatedAtLt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrCreatedAtLt(createdAt time.Time) PostQuerySet {
	return qs.w(qs.db.Or(clause.Lt{Column: "created_at", Value: createdAt}))
}

// OrCreatedAtLte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrCreatedAtLte(createdAt time.Time) PostQuerySet {
	return qs.w(qs.db.Or(clause.Lte{Column: "created_at", Value: createdAt}))
}

// OrCreatedAtNe is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrCreatedAtNe(createdAt time.Time) PostQuerySet {
	return qs.w(qs.db.Or(clause.Neq{Column: "created_at", Value: createdAt}))
}

// OrIDEq is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrIDEq(ID uint) PostQuerySet {
	return qs.w(qs.db.Or(clause.Eq{Column: "id", Value: ID}))
}

// OrIDGt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrIDGt(ID uint) PostQuerySet {
	return qs.w(qs.db.Or(clause.Gt{Column: "id", Value: ID}))
}

// OrIDGte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrIDGte(ID uint) PostQuerySet {
	return qs.w(qs.db.Or(clause.Gte{Column: "id", Value: ID}))
}

// OrIDIn is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrIDIn(ID ...uint) PostQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in OrIDIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(ID))
	for i, s := range ID {
		values[i] = s
	}
	return qs.w(qs.db.Or(clause.IN{Column: "id", Values: values}))
}

// OrIDLt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrIDLt(ID uint) PostQuerySet {
	return qs.w(qs.db.Or(clause.Lt{Column: "id", Value: ID}))
}

// OrIDLte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrIDLte(ID uint) PostQuerySet {
	return qs.w(qs.db.Or(clause.Lte{Column: "id", Value: ID}))
}

// OrIDNe is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrIDNe(ID uint) PostQuerySet {
	return qs.w(qs.db.Or(clause.Neq{Column: "id", Value: ID}))
}

// OrIDNotIn is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrIDNotIn(ID ...uint) PostQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in OrIDNotIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(ID))
	for i, s := range ID {
		values[i] = s
	}
	return qs.w(qs.db.Or(clause.Not(clause.IN{Column: "id", Values: values})))
}

// OrStrEq is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrStrEq(str tmp.StringDef) PostQuerySet {
	return qs.w(qs.db.Or(clause.Eq{Column: "str", Value: str}))
}

// OrStrGt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrStrGt(str tmp.StringDef) PostQuerySet {
	return qs.w(qs.db.Or(clause.Gt{Column: "str", Value: str}))
}

// OrStrGte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrStrGte(str tmp.StringDef) PostQuerySet {
	return qs.w(qs.db.Or(clause.Gte{Column: "str", Value: str}))
}

// OrStrIn is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrStrIn(str ...tmp.StringDef) PostQuerySet {
	if len(str) == 0 {
		qs.db.AddError(errors.New("must at least pass one str in OrStrIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(str))
	for i, s := range str {
		values[i] = s
	}
	return qs.w(qs.db.Or(clause.IN{Column: "str", Values: values}))
}

// OrStrLike is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrStrLike(str tmp.StringDef) PostQuerySet {
	return qs.w(qs.db.Or(clause.Like{Column: "str", Value: str}))
}

// OrStrLt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrStrLt(str tmp.StringDef) PostQuerySet {
	return qs.w(qs.db.Or(clause.Lt{Column: "str", Value: str}))
}

// OrStrLte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrStrLte(str tmp.StringDef) PostQuerySet {
	return qs.w(qs.db.Or(clause.Lte{Column: "str", Value: str}))
}

// OrStrNe is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrStrNe(str tmp.StringDef) PostQuerySet {
	return qs.w(qs.db.Or(clause.Neq{Column: "str", Value: str}))
}

// OrStrNotIn is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrStrNotIn(str ...tmp.StringDef) PostQuerySet {
	if len(str) == 0 {
		qs.db.AddError(errors.New("must at least pass one str in OrStrNotIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(str))
	for i, s := range str {
		values[i] = s
	}
	return qs.w(qs.db.Or(clause.Not(clause.IN{Column: "str", Values: values})))
}

// OrStrNotLike is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrStrNotLike(str tmp.StringDef) PostQuerySet {
	return qs.w(qs.db.Or(clause.Not(clause.Like{Column: "str", Value: str})))
}

// OrTitleEq is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrTitleEq(title string) PostQuerySet {
	return qs.w(qs.db.Or(clause.Eq{Column: "title", Value: title}))
}

// OrTitleGt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrTitleGt(title string) PostQuerySet {
	return qs.w(qs.db.Or(clause.Gt{Column: "title", Value: title}))
}

// OrTitleGte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrTitleGte(title string) PostQuerySet {
	return qs.w(qs.db.Or(clause.Gte{Column: "title", Value: title}))
}

// OrTitleIn is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrTitleIn(title ...string) PostQuerySet {
	if len(title) == 0 {
		qs.db.AddError(errors.New("must at least pass one title in OrTitleIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(title))
	for i, s := range title {
		values[i] = s
	}
	return qs.w(qs.db.Or(clause.IN{Column: "title", Values: values}))
}

// OrTitleIsNotNull is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrTitleIsNotNull() PostQuerySet {
	return qs.w(qs.db.Or("title IS NOT NULL"))
}

// OrTitleIsNull is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrTitleIsNull() PostQuerySet {
	return qs.w(qs.db.Or("title IS NULL"))
}

// OrTitleLike is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrTitleLike(title string) PostQuerySet {
	return qs.w(qs.db.Or(clause.Like{Column: "title", Value: title}))
}

// OrTitleLt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrTitleLt(title string) PostQuerySet {
	return qs.w(qs.db.Or(clause.Lt{Column: "title", Value: title}))
}

// OrTitleLte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrTitleLte(title string) PostQuerySet {
	return qs.w(qs.db.Or(clause.Lte{Column: "title", Value: title}))
}

// OrTitleNe is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrTitleNe(title string) PostQuerySet {
	return qs.w(qs.db.Or(clause.Neq{Column: "title", Value: title}))
}

// OrTitleNotIn is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrTitleNotIn(title ...string) PostQuerySet {
	if len(title) == 0 {
		qs.db.AddError(errors.New("must at least pass one title in OrTitleNotIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(title))
	for i, s := range title {
		values[i] = s
	}
	return qs.w(qs.db.Or(clause.Not(clause.IN{Column: "title", Values: values})))
}

// OrTitleNotLike is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrTitleNotLike(title string) PostQuerySet {
	return qs.w(qs.db.Or(clause.Not(clause.Like{Column: "title", Value: title})))
}

// OrUpdatedAtEq is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrUpdatedAtEq(updatedAt time.Time) PostQuerySet {
	return qs.w(qs.db.Or(clause.Eq{Column: "updated_at", Value: updatedAt}))
}

// OrUpdatedAtGt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrUpdatedAtGt(updatedAt time.Time) PostQuerySet {
	return qs.w(qs.db.Or(clause.Gt{Column: "updated_at", Value: updatedAt}))
}

// OrUpdatedAtGte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrUpdatedAtGte(updatedAt time.Time) PostQuerySet {
	return qs.w(qs.db.Or(clause.Gte{Column: "updated_at", Value: updatedAt}))
}

// OrUpdatedAtLt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrUpdatedAtLt(updatedAt time.Time) PostQuerySet {
	return qs.w(qs.db.Or(clause.Lt{Column: "updated_at", Value: updatedAt}))
}

// OrUpdatedAtLte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrUpdatedAtLte(updatedAt time.Time) PostQuerySet {
	return qs.w(qs.db.Or(clause.Lte{Column: "updated_at", Value: updatedAt}))
}

// OrUpdatedAtNe is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrUpdatedAtNe(updatedAt time.Time) PostQuerySet {
	return qs.w(qs.db.Or(clause.Neq{Column: "updated_at", Value: updatedAt}))
}

// OrderAscByCreatedAt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrderAscByCreatedAt() PostQuerySet {
	return qs.w(qs.db.Order("created_at ASC"))
}

// OrderAscByID is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrderAscByID() PostQuerySet {
	return qs.w(qs.db.Order("id ASC"))
}

// OrderAscByStr is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrderAscByStr() PostQuerySet {
	return qs.w(qs.db.Order("str ASC"))
}

// OrderAscByTitle is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrderAscByTitle() PostQuerySet {
	return qs.w(qs.db.Order("title ASC"))
}

// OrderAscByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrderAscByUpdatedAt() PostQuerySet {
	return qs.w(qs.db.Order("updated_at ASC"))
}

// OrderDescByCreatedAt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrderDescByCreatedAt() PostQuerySet {
	return qs.w(qs.db.Order("created_at DESC"))
}

// OrderDescByID is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrderDescByID() PostQuerySet {
	return qs.w(qs.db.Order("id DESC"))
}

// OrderDescByStr is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrderDescByStr() PostQuerySet {
	return qs.w(qs.db.Order("str DESC"))
}

// OrderDescByTitle is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrderDescByTitle() PostQuerySet {
	return qs.w(qs.db.Order("title DESC"))
}

// OrderDescByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) OrderDescByUpdatedAt() PostQuerySet {
	return qs.w(qs.db.Order("updated_at DESC"))
}

// PreloadBlog is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) PreloadBlog() PostQuerySet {
	return qs.w(qs.db.Preload("Blog"))
}

// PreloadDeletedAt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) PreloadDeletedAt() PostQuerySet {
	return qs.w(qs.db.Preload("DeletedAt"))
}

// PreloadUser is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) PreloadUser() PostQuerySet {
	return qs.w(qs.db.Preload("User"))
}

// StrEq is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) StrEq(str tmp.StringDef) PostQuerySet {
	return qs.w(qs.db.Where(clause.Eq{Column: "str", Value: str}))
}

// StrGt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) StrGt(str tmp.StringDef) PostQuerySet {
	return qs.w(qs.db.Where(clause.Gt{Column: "str", Value: str}))
}

// StrGte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) StrGte(str tmp.StringDef) PostQuerySet {
	return qs.w(qs.db.Where(clause.Gte{Column: "str", Value: str}))
}

// StrIn is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) StrIn(str ...tmp.StringDef) PostQuerySet {
	if len(str) == 0 {
		qs.db.AddError(errors.New("must at least pass one str in StrIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(str))
	for i, s := range str {
		values[i] = s
	}
	return qs.w(qs.db.Where(clause.IN{Column: "str", Values: values}))
}

// StrLike is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) StrLike(str tmp.StringDef) PostQuerySet {
	return qs.w(qs.db.Where(clause.Like{Column: "str", Value: str}))
}

// StrLt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) StrLt(str tmp.StringDef) PostQuerySet {
	return qs.w(qs.db.Where(clause.Lt{Column: "str", Value: str}))
}

// StrLte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) StrLte(str tmp.StringDef) PostQuerySet {
	return qs.w(qs.db.Where(clause.Lte{Column: "str", Value: str}))
}

// StrNe is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) StrNe(str tmp.StringDef) PostQuerySet {
	return qs.w(qs.db.Where(clause.Neq{Column: "str", Value: str}))
}

// StrNotIn is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) StrNotIn(str ...tmp.StringDef) PostQuerySet {
	if len(str) == 0 {
		qs.db.AddError(errors.New("must at least pass one str in StrNotIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(str))
	for i, s := range str {
		values[i] = s
	}
	return qs.w(qs.db.Where(clause.Not(clause.IN{Column: "str", Values: values})))
}

// StrNotLike is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) StrNotLike(str tmp.StringDef) PostQuerySet {
	return qs.w(qs.db.Where(clause.Not(clause.Like{Column: "str", Value: str})))
}

// TitleEq is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) TitleEq(title string) PostQuerySet {
	return qs.w(qs.db.Where(clause.Eq{Column: "title", Value: title}))
}

// TitleGt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) TitleGt(title string) PostQuerySet {
	return qs.w(qs.db.Where(clause.Gt{Column: "title", Value: title}))
}

// TitleGte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) TitleGte(title string) PostQuerySet {
	return qs.w(qs.db.Where(clause.Gte{Column: "title", Value: title}))
}

// TitleIn is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) TitleIn(title ...string) PostQuerySet {
	if len(title) == 0 {
		qs.db.AddError(errors.New("must at least pass one title in TitleIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(title))
	for i, s := range title {
		values[i] = s
	}
	return qs.w(qs.db.Where(clause.IN{Column: "title", Values: values}))
}

// TitleIsNotNull is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) TitleIsNotNull() PostQuerySet {
	return qs.w(qs.db.Where("title IS NOT NULL"))
}

// TitleIsNull is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) TitleIsNull() PostQuerySet {
	return qs.w(qs.db.Where("title IS NULL"))
}

// TitleLike is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) TitleLike(title string) PostQuerySet {
	return qs.w(qs.db.Where(clause.Like{Column: "title", Value: title}))
}

// TitleLt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) TitleLt(title string) PostQuerySet {
	return qs.w(qs.db.Where(clause.Lt{Column: "title", Value: title}))
}

// TitleLte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) TitleLte(title string) PostQuerySet {
	return qs.w(qs.db.Where(clause.Lte{Column: "title", Value: title}))
}

// TitleNe is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) TitleNe(title string) PostQuerySet {
	return qs.w(qs.db.Where(clause.Neq{Column: "title", Value: title}))
}

// TitleNotIn is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) TitleNotIn(title ...string) PostQuerySet {
	if len(title) == 0 {
		qs.db.AddError(errors.New("must at least pass one title in TitleNotIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(title))
	for i, s := range title {
		values[i] = s
	}
	return qs.w(qs.db.Where(clause.Not(clause.IN{Column: "title", Values: values})))
}

// TitleNotLike is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) TitleNotLike(title string) PostQuerySet {
	return qs.w(qs.db.Where(clause.Not(clause.Like{Column: "title", Value: title})))
}

// UpdatedAtEq is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) UpdatedAtEq(updatedAt time.Time) PostQuerySet {
	return qs.w(qs.db.Where(clause.Eq{Column: "updated_at", Value: updatedAt}))
}

// UpdatedAtGt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) UpdatedAtGt(updatedAt time.Time) PostQuerySet {
	return qs.w(qs.db.Where(clause.Gt{Column: "updated_at", Value: updatedAt}))
}

// UpdatedAtGte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) UpdatedAtGte(updatedAt time.Time) PostQuerySet {
	return qs.w(qs.db.Where(clause.Gte{Column: "updated_at", Value: updatedAt}))
}

// UpdatedAtLt is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) UpdatedAtLt(updatedAt time.Time) PostQuerySet {
	return qs.w(qs.db.Where(clause.Lt{Column: "updated_at", Value: updatedAt}))
}

// UpdatedAtLte is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) UpdatedAtLte(updatedAt time.Time) PostQuerySet {
	return qs.w(qs.db.Where(clause.Lte{Column: "updated_at", Value: updatedAt}))
}

// UpdatedAtNe is an autogenerated method
// nolint: dupl
func (qs PostQuerySet) UpdatedAtNe(updatedAt time.Time) PostQuerySet {
	return qs.w(qs.db.Where(clause.Neq{Column: "updated_at", Value: updatedAt}))
}

// SetCreatedAt is an autogenerated method
// nolint: dupl
func (u PostUpdater) SetCreatedAt(createdAt time.Time) PostUpdater {
	u.fields[string(PostDBSchema.CreatedAt)] = createdAt
	return u
}

// SetDeletedAt is an autogenerated method
// nolint: dupl
func (u PostUpdater) SetDeletedAt(deletedAt gorm.DeletedAt) PostUpdater {
	u.fields[string(PostDBSchema.DeletedAt)] = deletedAt
	return u
}

// SetID is an autogenerated method
// nolint: dupl
func (u PostUpdater) SetID(ID uint) PostUpdater {
	u.fields[string(PostDBSchema.ID)] = ID
	return u
}

// SetStr is an autogenerated method
// nolint: dupl
func (u PostUpdater) SetStr(str tmp.StringDef) PostUpdater {
	u.fields[string(PostDBSchema.Str)] = str
	return u
}

// SetTitle is an autogenerated method
// nolint: dupl
func (u PostUpdater) SetTitle(title *string) PostUpdater {
	u.fields[string(PostDBSchema.Title)] = title
	return u
}

// SetUpdatedAt is an autogenerated method
// nolint: dupl
func (u PostUpdater) SetUpdatedAt(updatedAt time.Time) PostUpdater {
	u.fields[string(PostDBSchema.UpdatedAt)] = updatedAt
	return u
}

// SetUser is an autogenerated method
// nolint: dupl
func (u PostUpdater) SetUser(user User) PostUpdater {
	u.fields[string(PostDBSchema.User)] = user
	return u
}

// Update is an autogenerated method
// nolint: dupl
func (u PostUpdater) Update() error {
	return u.db.Updates(u.fields).Error
}

// UpdateNum is an autogenerated method
// nolint: dupl
func (u PostUpdater) UpdateNum() (int64, error) {
	db := u.db.Updates(u.fields)
	return db.RowsAffected, db.Error
}

// ===== END of query set PostQuerySet

// ===== BEGIN of Post modifiers

// PostDBSchemaField describes database schema field. It requires for method 'Update'
type PostDBSchemaField string

// String method returns string representation of field.
// nolint: dupl
func (f PostDBSchemaField) String() string {
	return string(f)
}

// PostDBSchema stores db field names of Post
var PostDBSchema = struct {
	ID        PostDBSchemaField
	CreatedAt PostDBSchemaField
	UpdatedAt PostDBSchemaField
	DeletedAt PostDBSchemaField
	Blog      PostDBSchemaField
	User      PostDBSchemaField
	Title     PostDBSchemaField
	Str       PostDBSchemaField
}{

	ID:        PostDBSchemaField("id"),
	CreatedAt: PostDBSchemaField("created_at"),
	UpdatedAt: PostDBSchemaField("updated_at"),
	DeletedAt: PostDBSchemaField("deleted_at"),
	Blog:      PostDBSchemaField("blog"),
	User:      PostDBSchemaField("user"),
	Title:     PostDBSchemaField("title"),
	Str:       PostDBSchemaField("str"),
}

var PostDBSchemaAllFields = []PostDBSchemaField{

	PostDBSchema.ID,
	PostDBSchema.CreatedAt,
	PostDBSchema.UpdatedAt,
	PostDBSchema.DeletedAt,
	PostDBSchema.Blog,
	PostDBSchema.User,
	PostDBSchema.Title,
	PostDBSchema.Str,
}

// Update updates Post fields by primary key
// nolint: dupl
func (o *Post) Update(db *gorm.DB, fields ...PostDBSchemaField) error {
	dbNameToFieldName := map[string]interface{}{
		"id":         o.ID,
		"created_at": o.CreatedAt,
		"updated_at": o.UpdatedAt,
		"deleted_at": o.DeletedAt,
		"blog":       o.Blog,
		"user":       o.User,
		"title":      o.Title,
		"str":        o.Str,
	}
	u := map[string]interface{}{}
	for _, f := range fields {
		fs := f.String()
		u[fs] = dbNameToFieldName[fs]
	}
	if err := db.Model(o).Updates(u).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return err
		}

		return fmt.Errorf("can't update Post %v fields %v: %s",
			o, fields, err)
	}

	return nil
}

// PostUpdater is an Post updates manager
type PostUpdater struct {
	fields map[string]interface{}
	db     *gorm.DB
}

// NewPostUpdater creates new Post updater
// nolint: dupl
func NewPostUpdater(db *gorm.DB) PostUpdater {
	return PostUpdater{
		fields: map[string]interface{}{},
		db:     db.Model(&Post{}),
	}
}

// ===== END of Post modifiers

// ===== BEGIN of query set UserQuerySet

// UserQuerySet is an queryset type for User
type UserQuerySet struct {
	db *gorm.DB
}

// NewUserQuerySet constructs new UserQuerySet
func NewUserQuerySet(db *gorm.DB) UserQuerySet {
	return UserQuerySet{
		db: db.Model(&User{}),
	}
}

func (qs UserQuerySet) w(db *gorm.DB) UserQuerySet {
	return NewUserQuerySet(db)
}

func (qs UserQuerySet) Select(fields ...UserDBSchemaField) UserQuerySet {
	names := []string{}
	for _, f := range fields {
		names = append(names, f.String())
	}

	return qs.w(qs.db.Select(names))
}

// Create is an autogenerated method
// nolint: dupl
func (o *User) Create(db *gorm.DB) error {
	return db.Create(o).Error
}

// Delete is an autogenerated method
// nolint: dupl
func (o *User) Delete(db *gorm.DB) error {
	return db.Delete(o).Error
}

// All is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) All(ret *[]User) error {
	return qs.db.Find(ret).Error
}

// Count is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) Count() (int64, error) {
	var count int64
	err := qs.db.Count(&count).Error
	return count, err
}

// CreatedAtEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) CreatedAtEq(createdAt time.Time) UserQuerySet {
	return qs.w(qs.db.Where(clause.Eq{Column: "created_at", Value: createdAt}))
}

// CreatedAtGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) CreatedAtGt(createdAt time.Time) UserQuerySet {
	return qs.w(qs.db.Where(clause.Gt{Column: "created_at", Value: createdAt}))
}

// CreatedAtGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) CreatedAtGte(createdAt time.Time) UserQuerySet {
	return qs.w(qs.db.Where(clause.Gte{Column: "created_at", Value: createdAt}))
}

// CreatedAtLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) CreatedAtLt(createdAt time.Time) UserQuerySet {
	return qs.w(qs.db.Where(clause.Lt{Column: "created_at", Value: createdAt}))
}

// CreatedAtLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) CreatedAtLte(createdAt time.Time) UserQuerySet {
	return qs.w(qs.db.Where(clause.Lte{Column: "created_at", Value: createdAt}))
}

// CreatedAtNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) CreatedAtNe(createdAt time.Time) UserQuerySet {
	return qs.w(qs.db.Where(clause.Neq{Column: "created_at", Value: createdAt}))
}

// Delete is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) Delete() error {
	return qs.db.Delete(&User{}).Error
}

// DeleteNum is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) DeleteNum() (int64, error) {
	db := qs.db.Delete(&User{})
	return db.RowsAffected, db.Error
}

// DeleteNumUnscoped is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) DeleteNumUnscoped() (int64, error) {
	db := qs.db.Unscoped().Delete(&User{})
	return db.RowsAffected, db.Error
}

// EmailEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) EmailEq(email string) UserQuerySet {
	return qs.w(qs.db.Where(clause.Eq{Column: "email", Value: email}))
}

// EmailGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) EmailGt(email string) UserQuerySet {
	return qs.w(qs.db.Where(clause.Gt{Column: "email", Value: email}))
}

// EmailGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) EmailGte(email string) UserQuerySet {
	return qs.w(qs.db.Where(clause.Gte{Column: "email", Value: email}))
}

// EmailIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) EmailIn(email ...string) UserQuerySet {
	if len(email) == 0 {
		qs.db.AddError(errors.New("must at least pass one email in EmailIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(email))
	for i, s := range email {
		values[i] = s
	}
	return qs.w(qs.db.Where(clause.IN{Column: "email", Values: values}))
}

// EmailLike is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) EmailLike(email string) UserQuerySet {
	return qs.w(qs.db.Where(clause.Like{Column: "email", Value: email}))
}

// EmailLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) EmailLt(email string) UserQuerySet {
	return qs.w(qs.db.Where(clause.Lt{Column: "email", Value: email}))
}

// EmailLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) EmailLte(email string) UserQuerySet {
	return qs.w(qs.db.Where(clause.Lte{Column: "email", Value: email}))
}

// EmailNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) EmailNe(email string) UserQuerySet {
	return qs.w(qs.db.Where(clause.Neq{Column: "email", Value: email}))
}

// EmailNotIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) EmailNotIn(email ...string) UserQuerySet {
	if len(email) == 0 {
		qs.db.AddError(errors.New("must at least pass one email in EmailNotIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(email))
	for i, s := range email {
		values[i] = s
	}
	return qs.w(qs.db.Where(clause.Not(clause.IN{Column: "email", Values: values})))
}

// EmailNotLike is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) EmailNotLike(email string) UserQuerySet {
	return qs.w(qs.db.Where(clause.Not(clause.Like{Column: "email", Value: email})))
}

// GetDB is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) GetDB() *gorm.DB {
	return qs.db
}

// GetUpdater is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) GetUpdater() UserUpdater {
	return NewUserUpdater(qs.db)
}

// IDEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) IDEq(ID uint) UserQuerySet {
	return qs.w(qs.db.Where(clause.Eq{Column: "id", Value: ID}))
}

// IDGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) IDGt(ID uint) UserQuerySet {
	return qs.w(qs.db.Where(clause.Gt{Column: "id", Value: ID}))
}

// IDGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) IDGte(ID uint) UserQuerySet {
	return qs.w(qs.db.Where(clause.Gte{Column: "id", Value: ID}))
}

// IDIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) IDIn(ID ...uint) UserQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in IDIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(ID))
	for i, s := range ID {
		values[i] = s
	}
	return qs.w(qs.db.Where(clause.IN{Column: "id", Values: values}))
}

// IDLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) IDLt(ID uint) UserQuerySet {
	return qs.w(qs.db.Where(clause.Lt{Column: "id", Value: ID}))
}

// IDLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) IDLte(ID uint) UserQuerySet {
	return qs.w(qs.db.Where(clause.Lte{Column: "id", Value: ID}))
}

// IDNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) IDNe(ID uint) UserQuerySet {
	return qs.w(qs.db.Where(clause.Neq{Column: "id", Value: ID}))
}

// IDNotIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) IDNotIn(ID ...uint) UserQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in IDNotIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(ID))
	for i, s := range ID {
		values[i] = s
	}
	return qs.w(qs.db.Where(clause.Not(clause.IN{Column: "id", Values: values})))
}

// Limit is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) Limit(limit int) UserQuerySet {
	return qs.w(qs.db.Limit(limit))
}

// NameEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) NameEq(name string) UserQuerySet {
	return qs.w(qs.db.Where(clause.Eq{Column: "name", Value: name}))
}

// NameGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) NameGt(name string) UserQuerySet {
	return qs.w(qs.db.Where(clause.Gt{Column: "name", Value: name}))
}

// NameGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) NameGte(name string) UserQuerySet {
	return qs.w(qs.db.Where(clause.Gte{Column: "name", Value: name}))
}

// NameIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) NameIn(name ...string) UserQuerySet {
	if len(name) == 0 {
		qs.db.AddError(errors.New("must at least pass one name in NameIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(name))
	for i, s := range name {
		values[i] = s
	}
	return qs.w(qs.db.Where(clause.IN{Column: "name", Values: values}))
}

// NameLike is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) NameLike(name string) UserQuerySet {
	return qs.w(qs.db.Where(clause.Like{Column: "name", Value: name}))
}

// NameLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) NameLt(name string) UserQuerySet {
	return qs.w(qs.db.Where(clause.Lt{Column: "name", Value: name}))
}

// NameLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) NameLte(name string) UserQuerySet {
	return qs.w(qs.db.Where(clause.Lte{Column: "name", Value: name}))
}

// NameNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) NameNe(name string) UserQuerySet {
	return qs.w(qs.db.Where(clause.Neq{Column: "name", Value: name}))
}

// NameNotIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) NameNotIn(name ...string) UserQuerySet {
	if len(name) == 0 {
		qs.db.AddError(errors.New("must at least pass one name in NameNotIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(name))
	for i, s := range name {
		values[i] = s
	}
	return qs.w(qs.db.Where(clause.Not(clause.IN{Column: "name", Values: values})))
}

// NameNotLike is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) NameNotLike(name string) UserQuerySet {
	return qs.w(qs.db.Where(clause.Not(clause.Like{Column: "name", Value: name})))
}

// Offset is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) Offset(offset int) UserQuerySet {
	return qs.w(qs.db.Offset(offset))
}

// One is used to retrieve one result. It returns gorm.ErrRecordNotFound
// if nothing was fetched
func (qs UserQuerySet) One(ret *User) error {
	return qs.db.First(ret).Error
}

// OrCreatedAtEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrCreatedAtEq(createdAt time.Time) UserQuerySet {
	return qs.w(qs.db.Or(clause.Eq{Column: "created_at", Value: createdAt}))
}

// OrCreatedAtGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrCreatedAtGt(createdAt time.Time) UserQuerySet {
	return qs.w(qs.db.Or(clause.Gt{Column: "created_at", Value: createdAt}))
}

// OrCreatedAtGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrCreatedAtGte(createdAt time.Time) UserQuerySet {
	return qs.w(qs.db.Or(clause.Gte{Column: "created_at", Value: createdAt}))
}

// OrCreatedAtLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrCreatedAtLt(createdAt time.Time) UserQuerySet {
	return qs.w(qs.db.Or(clause.Lt{Column: "created_at", Value: createdAt}))
}

// OrCreatedAtLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrCreatedAtLte(createdAt time.Time) UserQuerySet {
	return qs.w(qs.db.Or(clause.Lte{Column: "created_at", Value: createdAt}))
}

// OrCreatedAtNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrCreatedAtNe(createdAt time.Time) UserQuerySet {
	return qs.w(qs.db.Or(clause.Neq{Column: "created_at", Value: createdAt}))
}

// OrEmailEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrEmailEq(email string) UserQuerySet {
	return qs.w(qs.db.Or(clause.Eq{Column: "email", Value: email}))
}

// OrEmailGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrEmailGt(email string) UserQuerySet {
	return qs.w(qs.db.Or(clause.Gt{Column: "email", Value: email}))
}

// OrEmailGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrEmailGte(email string) UserQuerySet {
	return qs.w(qs.db.Or(clause.Gte{Column: "email", Value: email}))
}

// OrEmailIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrEmailIn(email ...string) UserQuerySet {
	if len(email) == 0 {
		qs.db.AddError(errors.New("must at least pass one email in OrEmailIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(email))
	for i, s := range email {
		values[i] = s
	}
	return qs.w(qs.db.Or(clause.IN{Column: "email", Values: values}))
}

// OrEmailLike is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrEmailLike(email string) UserQuerySet {
	return qs.w(qs.db.Or(clause.Like{Column: "email", Value: email}))
}

// OrEmailLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrEmailLt(email string) UserQuerySet {
	return qs.w(qs.db.Or(clause.Lt{Column: "email", Value: email}))
}

// OrEmailLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrEmailLte(email string) UserQuerySet {
	return qs.w(qs.db.Or(clause.Lte{Column: "email", Value: email}))
}

// OrEmailNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrEmailNe(email string) UserQuerySet {
	return qs.w(qs.db.Or(clause.Neq{Column: "email", Value: email}))
}

// OrEmailNotIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrEmailNotIn(email ...string) UserQuerySet {
	if len(email) == 0 {
		qs.db.AddError(errors.New("must at least pass one email in OrEmailNotIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(email))
	for i, s := range email {
		values[i] = s
	}
	return qs.w(qs.db.Or(clause.Not(clause.IN{Column: "email", Values: values})))
}

// OrEmailNotLike is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrEmailNotLike(email string) UserQuerySet {
	return qs.w(qs.db.Or(clause.Not(clause.Like{Column: "email", Value: email})))
}

// OrIDEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrIDEq(ID uint) UserQuerySet {
	return qs.w(qs.db.Or(clause.Eq{Column: "id", Value: ID}))
}

// OrIDGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrIDGt(ID uint) UserQuerySet {
	return qs.w(qs.db.Or(clause.Gt{Column: "id", Value: ID}))
}

// OrIDGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrIDGte(ID uint) UserQuerySet {
	return qs.w(qs.db.Or(clause.Gte{Column: "id", Value: ID}))
}

// OrIDIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrIDIn(ID ...uint) UserQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in OrIDIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(ID))
	for i, s := range ID {
		values[i] = s
	}
	return qs.w(qs.db.Or(clause.IN{Column: "id", Values: values}))
}

// OrIDLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrIDLt(ID uint) UserQuerySet {
	return qs.w(qs.db.Or(clause.Lt{Column: "id", Value: ID}))
}

// OrIDLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrIDLte(ID uint) UserQuerySet {
	return qs.w(qs.db.Or(clause.Lte{Column: "id", Value: ID}))
}

// OrIDNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrIDNe(ID uint) UserQuerySet {
	return qs.w(qs.db.Or(clause.Neq{Column: "id", Value: ID}))
}

// OrIDNotIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrIDNotIn(ID ...uint) UserQuerySet {
	if len(ID) == 0 {
		qs.db.AddError(errors.New("must at least pass one ID in OrIDNotIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(ID))
	for i, s := range ID {
		values[i] = s
	}
	return qs.w(qs.db.Or(clause.Not(clause.IN{Column: "id", Values: values})))
}

// OrNameEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrNameEq(name string) UserQuerySet {
	return qs.w(qs.db.Or(clause.Eq{Column: "name", Value: name}))
}

// OrNameGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrNameGt(name string) UserQuerySet {
	return qs.w(qs.db.Or(clause.Gt{Column: "name", Value: name}))
}

// OrNameGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrNameGte(name string) UserQuerySet {
	return qs.w(qs.db.Or(clause.Gte{Column: "name", Value: name}))
}

// OrNameIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrNameIn(name ...string) UserQuerySet {
	if len(name) == 0 {
		qs.db.AddError(errors.New("must at least pass one name in OrNameIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(name))
	for i, s := range name {
		values[i] = s
	}
	return qs.w(qs.db.Or(clause.IN{Column: "name", Values: values}))
}

// OrNameLike is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrNameLike(name string) UserQuerySet {
	return qs.w(qs.db.Or(clause.Like{Column: "name", Value: name}))
}

// OrNameLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrNameLt(name string) UserQuerySet {
	return qs.w(qs.db.Or(clause.Lt{Column: "name", Value: name}))
}

// OrNameLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrNameLte(name string) UserQuerySet {
	return qs.w(qs.db.Or(clause.Lte{Column: "name", Value: name}))
}

// OrNameNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrNameNe(name string) UserQuerySet {
	return qs.w(qs.db.Or(clause.Neq{Column: "name", Value: name}))
}

// OrNameNotIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrNameNotIn(name ...string) UserQuerySet {
	if len(name) == 0 {
		qs.db.AddError(errors.New("must at least pass one name in OrNameNotIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(name))
	for i, s := range name {
		values[i] = s
	}
	return qs.w(qs.db.Or(clause.Not(clause.IN{Column: "name", Values: values})))
}

// OrNameNotLike is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrNameNotLike(name string) UserQuerySet {
	return qs.w(qs.db.Or(clause.Not(clause.Like{Column: "name", Value: name})))
}

// OrSurnameEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrSurnameEq(surname string) UserQuerySet {
	return qs.w(qs.db.Or(clause.Eq{Column: "user_surname", Value: surname}))
}

// OrSurnameGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrSurnameGt(surname string) UserQuerySet {
	return qs.w(qs.db.Or(clause.Gt{Column: "user_surname", Value: surname}))
}

// OrSurnameGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrSurnameGte(surname string) UserQuerySet {
	return qs.w(qs.db.Or(clause.Gte{Column: "user_surname", Value: surname}))
}

// OrSurnameIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrSurnameIn(surname ...string) UserQuerySet {
	if len(surname) == 0 {
		qs.db.AddError(errors.New("must at least pass one surname in OrSurnameIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(surname))
	for i, s := range surname {
		values[i] = s
	}
	return qs.w(qs.db.Or(clause.IN{Column: "user_surname", Values: values}))
}

// OrSurnameIsNotNull is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrSurnameIsNotNull() UserQuerySet {
	return qs.w(qs.db.Or("user_surname IS NOT NULL"))
}

// OrSurnameIsNull is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrSurnameIsNull() UserQuerySet {
	return qs.w(qs.db.Or("user_surname IS NULL"))
}

// OrSurnameLike is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrSurnameLike(surname string) UserQuerySet {
	return qs.w(qs.db.Or(clause.Like{Column: "user_surname", Value: surname}))
}

// OrSurnameLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrSurnameLt(surname string) UserQuerySet {
	return qs.w(qs.db.Or(clause.Lt{Column: "user_surname", Value: surname}))
}

// OrSurnameLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrSurnameLte(surname string) UserQuerySet {
	return qs.w(qs.db.Or(clause.Lte{Column: "user_surname", Value: surname}))
}

// OrSurnameNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrSurnameNe(surname string) UserQuerySet {
	return qs.w(qs.db.Or(clause.Neq{Column: "user_surname", Value: surname}))
}

// OrSurnameNotIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrSurnameNotIn(surname ...string) UserQuerySet {
	if len(surname) == 0 {
		qs.db.AddError(errors.New("must at least pass one surname in OrSurnameNotIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(surname))
	for i, s := range surname {
		values[i] = s
	}
	return qs.w(qs.db.Or(clause.Not(clause.IN{Column: "user_surname", Values: values})))
}

// OrSurnameNotLike is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrSurnameNotLike(surname string) UserQuerySet {
	return qs.w(qs.db.Or(clause.Not(clause.Like{Column: "user_surname", Value: surname})))
}

// OrUpdatedAtEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrUpdatedAtEq(updatedAt time.Time) UserQuerySet {
	return qs.w(qs.db.Or(clause.Eq{Column: "updated_at", Value: updatedAt}))
}

// OrUpdatedAtGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrUpdatedAtGt(updatedAt time.Time) UserQuerySet {
	return qs.w(qs.db.Or(clause.Gt{Column: "updated_at", Value: updatedAt}))
}

// OrUpdatedAtGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrUpdatedAtGte(updatedAt time.Time) UserQuerySet {
	return qs.w(qs.db.Or(clause.Gte{Column: "updated_at", Value: updatedAt}))
}

// OrUpdatedAtLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrUpdatedAtLt(updatedAt time.Time) UserQuerySet {
	return qs.w(qs.db.Or(clause.Lt{Column: "updated_at", Value: updatedAt}))
}

// OrUpdatedAtLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrUpdatedAtLte(updatedAt time.Time) UserQuerySet {
	return qs.w(qs.db.Or(clause.Lte{Column: "updated_at", Value: updatedAt}))
}

// OrUpdatedAtNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrUpdatedAtNe(updatedAt time.Time) UserQuerySet {
	return qs.w(qs.db.Or(clause.Neq{Column: "updated_at", Value: updatedAt}))
}

// OrderAscByCreatedAt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderAscByCreatedAt() UserQuerySet {
	return qs.w(qs.db.Order("created_at ASC"))
}

// OrderAscByEmail is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderAscByEmail() UserQuerySet {
	return qs.w(qs.db.Order("email ASC"))
}

// OrderAscByID is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderAscByID() UserQuerySet {
	return qs.w(qs.db.Order("id ASC"))
}

// OrderAscByName is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderAscByName() UserQuerySet {
	return qs.w(qs.db.Order("name ASC"))
}

// OrderAscBySurname is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderAscBySurname() UserQuerySet {
	return qs.w(qs.db.Order("user_surname ASC"))
}

// OrderAscByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderAscByUpdatedAt() UserQuerySet {
	return qs.w(qs.db.Order("updated_at ASC"))
}

// OrderDescByCreatedAt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderDescByCreatedAt() UserQuerySet {
	return qs.w(qs.db.Order("created_at DESC"))
}

// OrderDescByEmail is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderDescByEmail() UserQuerySet {
	return qs.w(qs.db.Order("email DESC"))
}

// OrderDescByID is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderDescByID() UserQuerySet {
	return qs.w(qs.db.Order("id DESC"))
}

// OrderDescByName is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderDescByName() UserQuerySet {
	return qs.w(qs.db.Order("name DESC"))
}

// OrderDescBySurname is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderDescBySurname() UserQuerySet {
	return qs.w(qs.db.Order("user_surname DESC"))
}

// OrderDescByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) OrderDescByUpdatedAt() UserQuerySet {
	return qs.w(qs.db.Order("updated_at DESC"))
}

// PreloadDeletedAt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) PreloadDeletedAt() UserQuerySet {
	return qs.w(qs.db.Preload("DeletedAt"))
}

// SurnameEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) SurnameEq(surname string) UserQuerySet {
	return qs.w(qs.db.Where(clause.Eq{Column: "user_surname", Value: surname}))
}

// SurnameGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) SurnameGt(surname string) UserQuerySet {
	return qs.w(qs.db.Where(clause.Gt{Column: "user_surname", Value: surname}))
}

// SurnameGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) SurnameGte(surname string) UserQuerySet {
	return qs.w(qs.db.Where(clause.Gte{Column: "user_surname", Value: surname}))
}

// SurnameIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) SurnameIn(surname ...string) UserQuerySet {
	if len(surname) == 0 {
		qs.db.AddError(errors.New("must at least pass one surname in SurnameIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(surname))
	for i, s := range surname {
		values[i] = s
	}
	return qs.w(qs.db.Where(clause.IN{Column: "user_surname", Values: values}))
}

// SurnameIsNotNull is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) SurnameIsNotNull() UserQuerySet {
	return qs.w(qs.db.Where("user_surname IS NOT NULL"))
}

// SurnameIsNull is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) SurnameIsNull() UserQuerySet {
	return qs.w(qs.db.Where("user_surname IS NULL"))
}

// SurnameLike is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) SurnameLike(surname string) UserQuerySet {
	return qs.w(qs.db.Where(clause.Like{Column: "user_surname", Value: surname}))
}

// SurnameLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) SurnameLt(surname string) UserQuerySet {
	return qs.w(qs.db.Where(clause.Lt{Column: "user_surname", Value: surname}))
}

// SurnameLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) SurnameLte(surname string) UserQuerySet {
	return qs.w(qs.db.Where(clause.Lte{Column: "user_surname", Value: surname}))
}

// SurnameNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) SurnameNe(surname string) UserQuerySet {
	return qs.w(qs.db.Where(clause.Neq{Column: "user_surname", Value: surname}))
}

// SurnameNotIn is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) SurnameNotIn(surname ...string) UserQuerySet {
	if len(surname) == 0 {
		qs.db.AddError(errors.New("must at least pass one surname in SurnameNotIn"))
		return qs.w(qs.db)
	}
	values := make([]interface{}, len(surname))
	for i, s := range surname {
		values[i] = s
	}
	return qs.w(qs.db.Where(clause.Not(clause.IN{Column: "user_surname", Values: values})))
}

// SurnameNotLike is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) SurnameNotLike(surname string) UserQuerySet {
	return qs.w(qs.db.Where(clause.Not(clause.Like{Column: "user_surname", Value: surname})))
}

// UpdatedAtEq is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) UpdatedAtEq(updatedAt time.Time) UserQuerySet {
	return qs.w(qs.db.Where(clause.Eq{Column: "updated_at", Value: updatedAt}))
}

// UpdatedAtGt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) UpdatedAtGt(updatedAt time.Time) UserQuerySet {
	return qs.w(qs.db.Where(clause.Gt{Column: "updated_at", Value: updatedAt}))
}

// UpdatedAtGte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) UpdatedAtGte(updatedAt time.Time) UserQuerySet {
	return qs.w(qs.db.Where(clause.Gte{Column: "updated_at", Value: updatedAt}))
}

// UpdatedAtLt is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) UpdatedAtLt(updatedAt time.Time) UserQuerySet {
	return qs.w(qs.db.Where(clause.Lt{Column: "updated_at", Value: updatedAt}))
}

// UpdatedAtLte is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) UpdatedAtLte(updatedAt time.Time) UserQuerySet {
	return qs.w(qs.db.Where(clause.Lte{Column: "updated_at", Value: updatedAt}))
}

// UpdatedAtNe is an autogenerated method
// nolint: dupl
func (qs UserQuerySet) UpdatedAtNe(updatedAt time.Time) UserQuerySet {
	return qs.w(qs.db.Where(clause.Neq{Column: "updated_at", Value: updatedAt}))
}

// SetCreatedAt is an autogenerated method
// nolint: dupl
func (u UserUpdater) SetCreatedAt(createdAt time.Time) UserUpdater {
	u.fields[string(UserDBSchema.CreatedAt)] = createdAt
	return u
}

// SetDeletedAt is an autogenerated method
// nolint: dupl
func (u UserUpdater) SetDeletedAt(deletedAt gorm.DeletedAt) UserUpdater {
	u.fields[string(UserDBSchema.DeletedAt)] = deletedAt
	return u
}

// SetEmail is an autogenerated method
// nolint: dupl
func (u UserUpdater) SetEmail(email string) UserUpdater {
	u.fields[string(UserDBSchema.Email)] = email
	return u
}

// SetID is an autogenerated method
// nolint: dupl
func (u UserUpdater) SetID(ID uint) UserUpdater {
	u.fields[string(UserDBSchema.ID)] = ID
	return u
}

// SetName is an autogenerated method
// nolint: dupl
func (u UserUpdater) SetName(name string) UserUpdater {
	u.fields[string(UserDBSchema.Name)] = name
	return u
}

// SetSurname is an autogenerated method
// nolint: dupl
func (u UserUpdater) SetSurname(surname *string) UserUpdater {
	u.fields[string(UserDBSchema.Surname)] = surname
	return u
}

// SetUpdatedAt is an autogenerated method
// nolint: dupl
func (u UserUpdater) SetUpdatedAt(updatedAt time.Time) UserUpdater {
	u.fields[string(UserDBSchema.UpdatedAt)] = updatedAt
	return u
}

// Update is an autogenerated method
// nolint: dupl
func (u UserUpdater) Update() error {
	return u.db.Updates(u.fields).Error
}

// UpdateNum is an autogenerated method
// nolint: dupl
func (u UserUpdater) UpdateNum() (int64, error) {
	db := u.db.Updates(u.fields)
	return db.RowsAffected, db.Error
}

// ===== END of query set UserQuerySet

// ===== BEGIN of User modifiers

// UserDBSchemaField describes database schema field. It requires for method 'Update'
type UserDBSchemaField string

// String method returns string representation of field.
// nolint: dupl
func (f UserDBSchemaField) String() string {
	return string(f)
}

// UserDBSchema stores db field names of User
var UserDBSchema = struct {
	ID        UserDBSchemaField
	CreatedAt UserDBSchemaField
	UpdatedAt UserDBSchemaField
	DeletedAt UserDBSchemaField
	Name      UserDBSchemaField
	Surname   UserDBSchemaField
	Email     UserDBSchemaField
}{

	ID:        UserDBSchemaField("id"),
	CreatedAt: UserDBSchemaField("created_at"),
	UpdatedAt: UserDBSchemaField("updated_at"),
	DeletedAt: UserDBSchemaField("deleted_at"),
	Name:      UserDBSchemaField("name"),
	Surname:   UserDBSchemaField("user_surname"),
	Email:     UserDBSchemaField("email"),
}

var UserDBSchemaAllFields = []UserDBSchemaField{

	UserDBSchema.ID,
	UserDBSchema.CreatedAt,
	UserDBSchema.UpdatedAt,
	UserDBSchema.DeletedAt,
	UserDBSchema.Name,
	UserDBSchema.Surname,
	UserDBSchema.Email,
}

// Update updates User fields by primary key
// nolint: dupl
func (o *User) Update(db *gorm.DB, fields ...UserDBSchemaField) error {
	dbNameToFieldName := map[string]interface{}{
		"id":           o.ID,
		"created_at":   o.CreatedAt,
		"updated_at":   o.UpdatedAt,
		"deleted_at":   o.DeletedAt,
		"name":         o.Name,
		"user_surname": o.Surname,
		"email":        o.Email,
	}
	u := map[string]interface{}{}
	for _, f := range fields {
		fs := f.String()
		u[fs] = dbNameToFieldName[fs]
	}
	if err := db.Model(o).Updates(u).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return err
		}

		return fmt.Errorf("can't update User %v fields %v: %s",
			o, fields, err)
	}

	return nil
}

// UserUpdater is an User updates manager
type UserUpdater struct {
	fields map[string]interface{}
	db     *gorm.DB
}

// NewUserUpdater creates new User updater
// nolint: dupl
func NewUserUpdater(db *gorm.DB) UserUpdater {
	return UserUpdater{
		fields: map[string]interface{}{},
		db:     db.Model(&User{}),
	}
}

// ===== END of User modifiers

// ===== END of all query sets
